name: 'Is First interaction'
description: 'Checks if contributor is new when they create their first issue or open their first pull request and optionally greet them'
author: 'GitHub'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  issue-message:
    description: 'Comment to post on an individual''s first issue'
  pr-message:
    description: 'Comment to post on an individual''s first pull request'
runs:
  using: 'docker'
  image: 'Dockerfile'
  